version: '3.7'

secrets:
  licensefile:
    file: ./service.txt
    
services:
  flexlm:
    build:
      context: .
      dockerfile: Dockerfile.flexlm
    image: flexlm:latest
    secrets:
      - licensefile
    environment:
      LICENSE: /run/secrets/licensefile
      FLASK_APP: webapp/start_app
      FLASK_ENV: production
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    command: ["/home/flexlm/miniconda3/bin/flask", "run"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .:/home/flexlm/webapp
    ports:
      - 5000:5000

