version: '3.7'

secrets:
  licensefile:
    file: ./service.txt
    
services:
  flexlm:
    image: flexlm:latest
    ports:
      - 5000:5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    secrets:
      - licensefile
    environment:
      LICENSE: /run/secrets/licensefile

    command: ["/run/secrets/licensefile"]
    
    build:
      context: .
      dockerfile: Dockerfile.flexlm

