version: '3.7'

services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    image: flexlm_monitor:latest
    environment:
      LICENSE: /home/flexlm/config/service.txt
      FLASK_APP: webapp/start_app
      FLASK_ENV: production
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    command: ["/home/flexlm/miniconda3/bin/flask", "run"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - .:/home/flexlm/webapp:ro
      - ./config:/home/flexlm/config:ro
    ports:
      - 5000:5000

