version: '3.7'

secrets:

services:
  flexlm:
    image: flexlm:latest
    ports:
      - 5000:5000
    volumes:
      - ./service.txt:/home/flexlm/service.txt:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ["/home/flexlm/sevice.txt"]
    build:
      context: .
      dockerfile: Dockerfile.flexlm

